/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
	export interface GlobalComponents {
		CropperUpload: typeof import("./src/components/Upload/CropperUpload/index.vue")["default"]
		ElAside: typeof import("element-plus/es")["ElAside"]
		ElAvatar: typeof import("element-plus/es")["ElAvatar"]
		ElButton: typeof import("element-plus/es")["ElButton"]
		ElCascader: typeof import("element-plus/es")["ElCascader"]
		ElConfigProvider: typeof import("element-plus/es")["ElConfigProvider"]
		ElContainer: typeof import("element-plus/es")["ElContainer"]
		ElDatePicker: typeof import("element-plus/es")["ElDatePicker"]
		ElDescriptions: typeof import("element-plus/es")["ElDescriptions"]
		ElDescriptionsItem: typeof import("element-plus/es")["ElDescriptionsItem"]
		ElDialog: typeof import("element-plus/es")["ElDialog"]
		ElDropdown: typeof import("element-plus/es")["ElDropdown"]
		ElDropdownItem: typeof import("element-plus/es")["ElDropdownItem"]
		ElDropdownMenu: typeof import("element-plus/es")["ElDropdownMenu"]
		ElEmpty: typeof import("element-plus/es")["ElEmpty"]
		ElForm: typeof import("element-plus/es")["ElForm"]
		ElFormItem: typeof import("element-plus/es")["ElFormItem"]
		ElHeader: typeof import("element-plus/es")["ElHeader"]
		ElIcon: typeof import("element-plus/es")["ElIcon"]
		ElInput: typeof import("element-plus/es")["ElInput"]
		ElInputNumber: typeof import("element-plus/es")["ElInputNumber"]
		ElMain: typeof import("element-plus/es")["ElMain"]
		ElMenu: typeof import("element-plus/es")["ElMenu"]
		ElMenuItem: typeof import("element-plus/es")["ElMenuItem"]
		ElOption: typeof import("element-plus/es")["ElOption"]
		ElPagination: typeof import("element-plus/es")["ElPagination"]
		ElPopconfirm: typeof import("element-plus/es")["ElPopconfirm"]
		ElPopover: typeof import("element-plus/es")["ElPopover"]
		ElRadio: typeof import("element-plus/es")["ElRadio"]
		ElRadioGroup: typeof import("element-plus/es")["ElRadioGroup"]
		ElScrollbar: typeof import("element-plus/es")["ElScrollbar"]
		ElSelect: typeof import("element-plus/es")["ElSelect"]
		ElSubMenu: typeof import("element-plus/es")["ElSubMenu"]
		ElSwitch: typeof import("element-plus/es")["ElSwitch"]
		ElTable: typeof import("element-plus/es")["ElTable"]
		ElTableColumn: typeof import("element-plus/es")["ElTableColumn"]
		ElTag: typeof import("element-plus/es")["ElTag"]
		ElTree: typeof import("element-plus/es")["ElTree"]
		ElUpload: typeof import("element-plus/es")["ElUpload"]
		Layout: typeof import("./src/components/layout/index.vue")["default"]
		MenuItem: typeof import("./src/components/layout/MenuItem.vue")["default"]
		MoreOperate: typeof import("./src/components/MoreOperate/index.vue")["default"]
		NavBar: typeof import("./src/components/layout/NavBar.vue")["default"]
		RemixIcon: typeof import("./src/components/SvgIcon/RemixIcon.vue")["default"]
		RouterLink: typeof import("vue-router")["RouterLink"]
		RouterView: typeof import("vue-router")["RouterView"]
		SideMenu: typeof import("./src/components/layout/SideMenu.vue")["default"]
		UploadCropper: typeof import("./src/components/Upload/CropperUpload/UploadCropper.vue")["default"]
	}
	export interface ComponentCustomProperties {
		vLoading: typeof import("element-plus/es")["ElLoadingDirective"]
	}
}
