/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
	export interface GlobalComponents {
		CropperUpload: typeof import("./src/components/Upload/CropperUpload/index.vue")["default"]
		ElAside: typeof import("element-plus/es")["ElAside"]
		ElAvatar: typeof import("element-plus/es")["ElAvatar"]
		ElContainer: typeof import("element-plus/es")["ElContainer"]
		ElForm: typeof import("element-plus/es")["ElForm"]
		ElFormItem: typeof import("element-plus/es")["ElFormItem"]
		ElHeader: typeof import("element-plus/es")["ElHeader"]
		ElIcon: typeof import("element-plus/es")["ElIcon"]
		ElInput: typeof import("element-plus/es")["ElInput"]
		ElMain: typeof import("element-plus/es")["ElMain"]
		ElMenu: typeof import("element-plus/es")["ElMenu"]
		ElMenuItem: typeof import("element-plus/es")["ElMenuItem"]
		ElPopover: typeof import("element-plus/es")["ElPopover"]
		ElScrollbar: typeof import("element-plus/es")["ElScrollbar"]
		ElSubMenu: typeof import("element-plus/es")["ElSubMenu"]
		Layout: typeof import("./src/components/layout/index.vue")["default"]
		MenuItem: typeof import("./src/components/layout/MenuItem.vue")["default"]
		MoreOperate: typeof import("./src/components/MoreOperate/index.vue")["default"]
		NavBar: typeof import("./src/components/layout/NavBar.vue")["default"]
		RemixIcon: typeof import("./src/components/SvgIcon/RemixIcon.vue")["default"]
		RouterLink: typeof import("vue-router")["RouterLink"]
		RouterView: typeof import("vue-router")["RouterView"]
		SideMenu: typeof import("./src/components/layout/SideMenu.vue")["default"]
		UploadCropper: typeof import("./src/components/Upload/CropperUpload/UploadCropper.vue")["default"]
	}
}
